=== flinteger/dnss-blocklists/sources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/ednsp/sources/schema.json",
  "type": "object",
  "title": "source schema",
  "description": "The filter source schema",
  "required": [
    "name",
    "description",
    "sources"
  ],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Filter list name",
      "description": "Filter list name",
      "default": ""
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "Filter description",
      "description": "Filter description",
      "default": ""
    },
    "sources": {
      "$id": "#/properties/sources",
      "type": "array",
      "title": "The filter sources",
      "description": "The filter sources.",
      "default": [],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/sources/items",
        "$ref": "#/definitions/source"
      }
    },
    "additions": {
      "$id": "#/properties/additions",
      "type": "array",
      "title": "Additional to filter",
      "description": "Additional to filter",
      "uniqueItems": true,
      "default": ""
    },
    "exclusions": {
      "$id": "#/properties/exclusions",
      "type": "array",
      "title": "Exclusions to filter",
      "description": "Excluded domains from filter, to solve false positive",
      "uniqueItems": true,
      "default": ""
    }
  },
  "definitions": {
    "source": {
      "type": "object",
      "title": "Filter source",
      "description": "Filter source.",
      "default": {},
      "required": [
        "url",
        "format"
      ],
      "properties": {
        "name": {
          "type": "string",
          "title": "Filter source name",
          "description": "Filter source name.",
          "default": ""
        },
        "website": {
          "type": "string",
          "title": "Website URL",
          "description": "Website URL.",
          "format": "uri",
          "pattern": "^(https?)://",
          "default": ""
        },
        "description": {
          "type": "string",
          "title": "Filter source description",
          "description": "Filter source description.",
          "default": ""
        },
        "license": {
          "type": "string",
          "title": "License",
          "description": "License type.",
          "enum": ["MIT", "GPLv3", "Unknown"],
          "default": ""
        },
        "license_url": {
          "type": "string",
          "title": "License URL",
          "description": "License URL.",
          "format": "uri",
          "pattern": "^(https?)://",
          "default": ""
        },
        "url": {
          "type": "string",
          "title": "Filter source url",
          "description": "Filter source url.",
          "default": ""
        },
        "format": {
          "type": "string",
          "title": "Filter source data format",
          "description": "Filter source data format.",
          "enum": ["hosts", "domains", "abp"],
          "default": ""
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== flinteger/dnss-blocklists/sources/ad.json
{
  "name": "ad",
  "description": "Ad and trackers, privacy",
  "sources": [
    {
      "name": "1Hosts (Lite)",
      "website": "https://github.com/badmojr/1Hosts",
      "description": "Protect your 'data' & eyeballs from being auctioned to the highest bidder.",
      "license": "Unknown",
      "url": "https://badmojr.github.io/1Hosts/Lite/domains.txt",
      "format": "domains"
    },
    {
      "name": "280blocker",
      "website": "https://280blocker.net",
      "description": "280blocker adblock domain lists (JP).",
      "license": "Unknown",
      "url": "https://280blocker.net/files/280blocker_domain.txt",
      "format": "domains"
    },
    {
      "name": "add.2o7Net",
      "website": "https://github.com/FadeMind/hosts.extras",
      "description": "2o7 Network tracking.",
      "license": "MIT",
      "license_url": "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/COPYING",
      "url": "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts",
      "format": "hosts"
    },
    {
      "name": "ad-wars",
      "description": "Ad (CN)",
      "website": "https://github.com/jdlingyu/ad-wars",
      "url": "https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts",
      "format": "hosts"
    },
    {
      "name": "AdAway",
      "website": "https://github.com/AdAway/adaway.github.io",
      "description": "Blocking mobile ad providers and some analytics providers.",
      "license": "GPLv3",
      "license_url": "https://raw.githubusercontent.com/AdAway/adaway.github.io/master/LICENSE.md",
      "url": "https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt",
      "format": "hosts"
    },
    {
      "name": "anti-AD",
      "website": "https://github.com/privacy-protection-tools/anti-AD",
      "description": "anti-AD是目前中文区命中率最高的广告过滤列表，实现了精确的广告屏蔽和隐私保护。",
      "license": "MIT",
      "license_url": "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/LICENSE",
      "url": "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt",
      "format": "domains"
    },
    {
      "name": "AdGuard DNS filter",
      "website": "https://github.com/AdguardTeam/AdguardSDNSFilter",
      "description": "A filter composed of several other filters (AdGuard Base filter, Social media filter, Tracking Protection filter, Mobile Ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.",
      "license": "GPLv3",
      "license_url": "https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/LICENSE",
      "url": "https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/rules.txt",
      "format": "abp"
    },
    {
      "name": "notracking/hosts-blocklists",
      "website": "https://github.com/notracking/hosts-blocklists",
      "description": "No more ads, tracking and other virtual garbage. All blocklists are gathered from multiple, actively maintained sources and automatically updated, cleaned, optimized and moderated on a daily basis.",
      "license": "Unknown",
      "url": "https://raw.githubusercontent.com/notracking/hosts-blocklists/master/dnscrypt-proxy/dnscrypt-proxy.blacklist.txt",
      "format": "domains"
    },
    {
      "name": "Cauchon/NSABlocklist-pi-hole-edition",
      "website": "https://github.com/Cauchon/NSABlocklist-pi-hole-edition",
      "description": "HOSTS file to block most known NSA / GCHQ / C.I.A. / F.B.I. spying servers. List is optimized for pi-hole.",
      "license": "MIT",
      "license_url": "https://raw.githubusercontent.com/Cauchon/NSABlocklist-pi-hole-edition/master/LICENSE",
      "url": "https://raw.githubusercontent.com/Cauchon/NSABlocklist-pi-hole-edition/master/HOSTS%20(excluding%20most%20GOV%20URLs)",
      "format": "domains"
    }
  ],
  "additions": [
    "ppt.ifsp.tv",
    "ppt.ifvod.tv"
  ],
  "exclusions": [
    "*.exacttarget.com",
    "148.xg4ken.com",
    "51.la",
    "ad.atdmt.com",
    "ad.doubleclick.net",
    "anyporn.com",
    "app.pendo.io",
    "bongacams.com",
    "browser-update.org",
    "click.redditmail.com",
    "clickserve.dartsearch.net",
    "cnzz.com",
    "coinpot.co",
    "cts.businesswire.com",
    "e-10077.adzerk.net",
    "exacttarget.com.edgekey.net",
    "get-express-vpn.com",
    "go.pardot.com",
    "googletagmanager.com",
    "goto-target-com.customtraffic.impactradius.com",
    "goto-walmart-com.ct.impactradius.com",
    "goto.walmart.com",
    "hotjar.com",
    "iesnare.com",
    "iqoption.com",
    "issuecdn.baidupcs.com",
    "lentainform.com",
    "livejasmin.com",
    "m.yap.yahoo.com",
    "marinetraffic.com",
    "my.nextdns.io",
    "nextdns.io",
    "nextdoor.com",
    "nexus.ensighten.com",
    "pi.pardot.com",
    "qualtrics.com",
    "rebrand.ly",
    "smartasset.com",
    "softonic.com",
    "statcounter.com",
    "survey.medallia.com",
    "sysdig.com",
    "thirdparty.bnc.lt",
    "to8to.com",
    "umeng.com",
    "uol.com.br",
    "vectorstock.com",
    "visitor.r20.constantcontact.com",
    "www-googletagmanager.l.google.com",
    "www.googleadservices.com",
    "www.googletagmanager.com",
    "www.rebrand.ly",
    "www.voiceads.cn",
    "xmrpool.net",
    "xnxx.com"
  ]
}

=== flinteger/dnss-blocklists/sources/porn.json
{
  "name": "porn",
  "description": "Porn",
  "sources": [
    {
      "url": "https://raw.githubusercontent.com/tiuxo/hosts/master/porn",
      "format": "hosts"
    },
    {
      "url": "https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts",
      "format": "hosts"
    },
    {
      "url": "https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt",
      "format": "hosts"
    },
    {
      "url": "https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts",
      "format": "hosts"
    }
  ],
  "exclusions": [
    "*.anonym.to",
    "*.cliqz.com",
    "*.dickssportinggoods.com",
    "*.fastpic.ru",
    "*.findicons.com",
    "*.jwpcdn.com",
    "*.meltwater.com",
    "*.openmultipleurl.com",
    "*.rebrand.ly",
    "*.scansafe.net",
    "*.sucuri.net",
    "*.x-diesel.com",
    "*.zaobao.com.sg",
    "barnfurnituremart.com"
  ],
  "additions": [
    "1.yetuav.top",
    "1.yetuav.xyz",
    "101277.com",
    "18avx.com",
    "1upsexer.com",
    "224gui.com",
    "56xx.top",
    "582898.com",
    "69hbook.com",
    "6z9.cc",
    "7xiu.cc",
    "8mk.cc",
    "adultdvdtalk.com",
    "adultdvdtalk.com",
    "adultfriendfinder.com",
    "adultgle.com",
    "agkywg.com",
    "avwong.com",
    "babes.com",
    "babestare.com",
    "bestporn.su",
    "canovel.com",
    "clipsbai.com",
    "crazyvideo.cyou",
    "dirtyindianporn.info",
    "doublelist.com",
    "dudu-sex.com",
    "fadama.com",
    "fanqianglu.com",
    "femefun.com",
    "fuckbooknigeria.com",
    "fuckbookzambia.com",
    "hairyolder.com",
    "hanime1.me",
    "heatedaffairs.com",
    "hlsapp.cc",
    "hlsdhoio.com",
    "hlsfrqug.com",
    "hlshowpq.show",
    "hlslhotf.com",
    "hlsqugfz.com",
    "hot-datings.life",
    "hotgaylist.com",
    "hotmovies.com",
    "hotsex.blog",
    "hotsex.cz",
    "hotzxgirl.com",
    "ijavhd.com",
    "jiatingseqing.com",
    "justindianpornx.com",
    "m.3movs.com",
    "myxxgirl.com",
    "nudegirls.wiki",
    "onlyindian.org",
    "peeperz.com",
    "pfbat.fit",
    "playboytv.com",
    "porn00.tv",
    "porn7.net",
    "pornbomb.cc",
    "pornhub-teen.com",
    "pornhub-x.net",
    "pornhub.run",
    "porniq.com",
    "pornone.com",
    "pornstar.gallery",
    "pornvideo.rodeo",
    "prettyvirgin.com",
    "qinav.com",
    "qinav.xyz",
    "qingse.one",
    "redbled.com",
    "rouav.com",
    "sextube.com",
    "sis001.com",
    "siszdaiy.com",
    "skipthegames.com",
    "sqhl68.com",
    "studentseemevery.buzz",
    "t66y.com",
    "uxzina.fit",
    "vsexy.lol",
    "wargers.org",
    "whichav.video",
    "whynotbi.com",
    "www.adultdvdtalk.com",
    "www.freeextremewebcams.com",
    "www.hotmovies.com",
    "www.instaboink.com",
    "www.pornstarpic.net",
    "www.redbled.com",
    "www.t66y.com",
    "wwwxvideo.org",
    "x-videos.me",
    "x-videos.ru",
    "xbookcn.net",
    "xinbochegn.com",
    "xporno.pics",
    "xteen.vip",
    "xvideo.bid",
    "xvideo.blue",
    "xvideo.party",
    "xvideo.run",
    "xvideos.co",
    "xvideos.es",
    "xxxdessert.com",
    "xxxvid.college",
    "xxxwow.net",
    "y1p.cc",
    "ychidd.com",
    "yetuav.top",
    "yetuav.xyz",
    "yetujs-baidu.com",
    "yetusp.com",
    "youporner.net"
  ]
}

=== flinteger/dnss-blocklists/sources/social_networks.json
{
  "name": "social_networks",
  "description": "Social networks",
  "sources": [
    {
      "name": "ut1-blacklist social networks",
      "description": "ut1-blacklist social networks",
      "url": "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/social_networks/domains",
      "format": "domains"
    }
  ],
  "additions": [
    "0.twitter.com",
    "api.facebook.com",
    "api.twitter.com",
    "facebook.com",
    "live.twitter.com",
    "m.facebook.com",
    "m.twitter.com",
    "mobile.twitter.com",
    "td.twitter.com",
    "tweetdeck.twitter.com",
    "twitter.com",
    "www.facebook.com",
    "www.twitter.com",
    "www2.twitter.com"
  ],
  "exclusions": [
    "*.edge-mqtt.facebook.com",
    "*.graph.facebook.com",
    "*.telegram.org",
    "*.whatsapp.com",
    "*.xx.fbcdn.net"
  ]
}

=== flinteger/dnss-blocklists/sources/game.json
{
  "name": "game",
  "description": "Game websites",
  "sources": [
    {
      "name": "ut1-blacklists games",
      "website": "https://raw.githubusercontent.com/olbat/ut1-blacklists",
      "description": "",
      "license": "Unknown",
      "url": "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/games/domains",
      "format": "domains"
    }
  ],
  "additions": [
    "hero-wars.com",
    "mathplayground.com",
    "onionfist.com",
    "www.mathplayground.com"
  ],
  "exclusions": [
  ]
}

=== flinteger/dnss-blocklists/sources/gambling.json
{
  "name": "gambling",
  "description": "Gambling",
  "sources": [
    {
      "name": "ut1-blacklists gambling",
      "description": "ut1-blacklists gambling",
      "url": "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/gambling/domains",
      "format": "domains"
    },
    {
      "name": "gambling-hosts",
      "description": "gambling-hosts",
      "url": "https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts",
      "format": "hosts"
    }
  ],
  "additions": [
    "qs8866.cc"
  ]
}

=== flinteger/dnss-blocklists/sources/dating.json
{
  "name": "dating",
  "description": "Dating",
  "sources": [
    {
      "name": "ut1-blacklists dating",
      "description": "ut1-blacklists dating",
      "url": "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/dating/domains",
      "format": "domains"
    }
  ],
  "additions": [
    "*.christianmingle.com",
    "*.eharmony.com",
    "*.elitesingles.com",
    "*.tinder.com",
    "*.zoosk.com",
    "api.dating.com",
    "badolov.com",
    "clubslane.com",
    "dating.silversingles.com",
    "iwillfindyou.love",
    "kismia.com",
    "myracinecounty.com",
    "okcupid.com",
    "seeking.com",
    "top10bestdatingsites.com",
    "top5-datingsites.com",
    "www.amolatina.com",
    "www.clickdate.com",
    "www.clubslane.com",
    "www.datemyage.com",
    "www.dating.com",
    "www.flirtstate.com",
    "www.iwillfindyou.love",
    "www.kismia.com",
    "www.losangelesmatchmaking.com",
    "www.losangelesprofessionalsingles.com",
    "www.lovevite.com",
    "www.match.com",
    "www.myracinecounty.com",
    "www.okcupid.com",
    "www.ourtime.com",
    "www.seeking.com",
    "www.silversingles.com",
    "www.trumingle.com",
    "www.ztattoo.com",
    "ztattoo.com"
  ]
}
